# Generated by Django 4.2.3 on 2023-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
